const initState ={
    brand:[
        {id:0, bgColor:"#660000", brandName:'budweiser', title:'Budweiser', description:'<p>Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created real-time 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement experiment lead to the “Show your true colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>The last project I worked on with Bud was the original Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/64225306' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/budRedlights.jpg', highlights:'<ul><li>Red Lights - Orginial Launch</li><li>Bud United - Show your true colours</li><li>Bud Light - Bobble heads</li><li>Kokanee - Next Ranger</li></ul>'},
        //
        {id:1, bgColor:"#3c6145", brandName:'roots', title:'Roots', description:'<p>Roots is expanding with physical stores in the US and Globally through their E-Comm site.  Moreover their E-Comm site is integrated into their instore POS system.  Did I mention that the POS system was based on windows 7 and IE?</p><p>Our job was to do the design, UX, and implementation of the presentation layer, on an aging Demandware(old commerce cloud) infrastructure.  Initially the site was not working on the POS systems.</p><p>Being the Lead Technologist on the project it was my job to travel onsite, diagnose, and propose a solution to the problem.  In the end, my recommendations not only helped get the POS system up and running for holiday sales, but it gave the Roots team the info they needed to get an upgrade to their POS system approved.</p>',hasVideo:false,vidURL:"",imageURL:'../../images/roots.jpg', highlights:'<ul><li>Fully Responsive</li><li>Managed teams in Montreal, Toronto, Vancouver, and India</li><li>Mobile Optimization</li></ul>'},
        //
        {id:2, bgColor:"#423735", brandName:'transistor', title:'Transistor Studios', description:'<p>I loved working in the states.  I was hired at Transistor to build their digital department after winning the Hyundai -Think About It- project from Goodby</p><p>The proof of concept was built by perfect fools, but there were issues during dev, that caused the Goodby team to look to Transistor, who had come up with the concept, to finish the solution</p><p>From there we made award winning work for brands like Pepsi Co, with Cheetos.com and the Now Propelled campaign. We did some innovative work with Sprint, integrating real-time gameplay with prerecorded assets and real-time 3D. And other fun projects for brands like Ray Ban, Dr. Pepper and Quaker.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/304152247' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/transistor.jpg', highlights:'<ul><li>Created Digital Discpline</li><li>Trained existined staff</li><li>Cheetos</li><li>Sprint</li><li>Hyundai</li><li>RayBan</li></ul>'},
        //
        {id:3, bgColor:"#9d4f16", brandName:'grip', title:'Grip Limited', description:'<p>When I started at Grip Limited, they were known as a "Mass Agency".  They had been trying to establish a digital department for a couple of years.  While they were able to produce some very compelling work, the process was painful for client, and unprofitable for the agency.</p><p>I was named as co-chair of the interactive management team, and personally tabled and championed the inclusion of social media as a discipline, as well was sit on the operations team with Randy Stein, spearheading the transformation of Grip from a mass, to media agonistic agency.</p><p>By the end of my tenure, digital revenue was up 400% and profitability was up 10 points.</p><p>With all of those wins, I still say my biggest contribution to the agency was cultural, as I fostered an environment of experimentation and learning.  Check out Budweiser for more on that.</p>',hasVideo:true,vidURL:"",imageURL:'../../images/grip.jpg', highlights:'<ul><li>Director of Production</li><li>Director of Innovation and Technology</li><li>Interactive Managment Team Chair</li><li>Operations and Change Managment</li><li>Mentorship and Learning</li></ul>'},
        //
        {id:4, bgColor:"#1c2a47", brandName:'hyundai', title:'Hyundai', description:'<p>Another brand near to my heart.  My mother convinced our entire family to exclusively buy Hyundai. Think About It was a dream campaign for me to work on.  It had high quality content, games, engaging visuals, and new technology few were familiar with at the time.  Such as AS3 and Papervision.</p><p>The initial build failed due to it spiking user memory into the Gigs, back in 2007, this was enough to crash a computer.  My task, along with Chris Eyerman of 3AM fame, was to redo the UX, and rebuild the app in a way to better manage memory.  The result is an international award winning site, and an international award winning campaign.</p><p>Today I am still working on Hyundai, maintaining and updating their Canadian dealer application.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/304151417' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/hyundai.jpg', highlights:'<ul><li>Think About It</li><li>Several Sales Events</li><li>Dealer Application</li><li>Driving too fast in an 1996 Sonota</li></ul>'},
        //
        {id:5, bgColor:"#a4151d", brandName:'stonemillbakehouse', title:'Stonemill Bakehouse', description:'<p>Stonemill is a Brand that everyone at Mass Minority should be proud of.  Almost everyone in the agency came together to re-launch the brand and help them expand into the mainstream.  We even won a Bessy for it.</p><p>I personally did the UX, lead development on the site as well as the ask me anything application.  And I also animated 4 spots for the Canada 150 celebration.  Not bad for a Director of Creative + Technology</p><p>The ask me anything application is pretty neat piece of code, that anticipates the answer it needs to serve up, and starts buffering the response before the user even asks the question.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/226305132' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/stonemill.jpg', highlights:'<ul><li>stonemillbakehouse.com</li><li>Ask me anything</li><li>150 Animations</li><li>Celebrate Slow</li></ul>'},
        //
        {id:6, bgColor:"#febb0f", brandName:'joeboxer', title:'Joe Boxer', description:'<p>Joe is a spunkey Canadia brand that screens fun.  Joe was one of our primary clients at Mass Minority, and our Joe was to relaunch the brand in time with the launch of their first E-comm platform</p><p>I was in charge of UX for the site, Technical Direction, as well as 1st AD on all broadcast shoots</p><p>For a very modest budget we were able to produce a years worth of social video content, a TV spot, and an E-comm site.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/218672174' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/joeBoxer.jpg', highlights:'<ul><li>joeboxer.ca</li><li>Social Media Strategy</li><li>E-comm Launch</li><li>Content Creation</li></ul>'},
        //
        {id:7, bgColor:"#be627a", brandName:'kraft', title:'Kraft', description:'<p>Kraft is one of the first Brands I worked with when I stumbbled upon advertizing.  I was priviledged enough to be both a technical and creative lead on Diamond Shreddies, winning a Bronze Pencil for art direction</p><p>That year I wokred on several award winnign campaigns for Kraft, including Maxwell House, brew some good, and Robinhood Flower</p><p>However my favorite Kraft project was an educational MMO for kids I designed for Kool-Aid called Kool Planet.  Kool Planet allowed children to complete educxational challenges, or real workd chores with their parents in exchange for a digital currency that allowed the kids to uild and share their own playgrounds.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/304512108 ' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/kraft.jpg', highlights:'<ul><li>Diamond Shreddies</li><li>Brew Some Good</li><li>Kool Planet</li><li>2 TDs during the anual Ogilvy/Kraft football game</li></ul>'},
        //
        {id:8, bgColor:"#4e3c61", brandName:'pepsi-co', title:'Pepsi Co', description:'<p>While working with Transistor and Goodby we did a significant amount of work for several Pepsi brands.</p><p>Cheetos.com was originally supposed to be a microsite called Cheetopia. My job was not only to build the core site and framework, but to also manage teams from 4 other companies. Development completed over the 2007 Xmas holidays.  The client was so pleased with the result, the microsite became the main brand site for years to come.</p><p>The nowPropelled app we built as a campaign piece for Propel Vitamin Water. You could enter up to 5 destinations and using the maps API and a bunch of custom server code, will give you the path of least resistance to do your chores. Choose from a pre-selected list of things like groceries or pharmacy. Or enter in exact addresses of where you want to go.</p>',hasVideo:true,vidURL:"<div class='embed-container'><iframe src='https://player.vimeo.com/video/225988640' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>",imageURL:'../../images/pepsico.jpg', highlights:'<ul><li>Cheetos.com</li><li>Legend of the Cheetocorn</li><li>Now Propelled</li><li>Gatorade</li></ul>'}
    ]
}
const workReducer =(state = initState, action) => {
    return state
}

export default workReducer