const initState ={
    brand:[
        {id:0, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'},
        //
        {id:2, title:'Budweiser', description:'<p>I started working on Budweiser after moving back to Canada from NYC.  Budweiser is a brand that one wants to over invest in.  Its iconic and bold, strong but fun.  Budweiser is also a brand that will reward overinvestment if it bears fruit.</p><p>Because of that dynamic, a dynamic shared by all inBev brands, I was able to allocate resources on my teams for research and development.  From those R&D hours we were able to create innovative and successful experience for inBev and their consumers.</p><p>Grip’s innovation team created realtime 3D and Physics engines for the web that led to the Bobbleheads campaign in both Canada and the USA.  Our dynamic color replacement expermine lead to the “Show your ture colours” Bud United app for the world cup.  Actively engaging 2.7 million people, and added close to a million new members to Budweiser’s facebook page.</p><p>And finally the last project I worked on with the brand, the orginial Redlight launch.  I can’t wait until the next time I get to create something unique and cool with these brands again.</p>',hasVideo:true,vidURL:'<iframe src="https://player.vimeo.com/video/64225306" width="640" height="559" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>',imageURL:'./images/budRedlights.jpg'}
    ]
}
const workReducer =(state = initState, action) => {
    return state
}

export default workReducer